/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Victor
 */
public class detail_prof extends javax.swing.JFrame {

    /**
     * Creates new form detail_prof
     */
     Liaison con= new Liaison();
    Statement stm;
    ResultSet Rs;
    PreparedStatement ps;
    public detail_prof() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmat = new javax.swing.JTextField();
        txtniv = new javax.swing.JTextField();
        txtpre = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Détails des enseignants");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(240, 10, 643, 100);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Prénom     :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(560, 50, 100, 22);

        label.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label.setText("Niveau d'enseignement    :");
        jPanel2.add(label);
        label.setBounds(30, 130, 200, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nom        :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 40, 90, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Matière enseignée    :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(500, 140, 153, 28);

        txtmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatActionPerformed(evt);
            }
        });
        jPanel2.add(txtmat);
        txtmat.setBounds(680, 140, 160, 30);

        txtniv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnivActionPerformed(evt);
            }
        });
        jPanel2.add(txtniv);
        txtniv.setBounds(240, 140, 150, 30);

        txtpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreActionPerformed(evt);
            }
        });
        jPanel2.add(txtpre);
        txtpre.setBounds(680, 40, 140, 30);

        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        jPanel2.add(txtno);
        txtno.setBounds(240, 40, 150, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(70, 190, 890, 280);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("ID      :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 120, 90, 30);
        getContentPane().add(txtid);
        txtid.setBounds(480, 120, 100, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 120, 140, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Retour au menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(840, 480, 170, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatActionPerformed

    private void txtnivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnivActionPerformed

    private void txtpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            stm=con.ObtenirConnexion().createStatement();
            ResultSet Rs=stm.executeQuery("Select nom,prenom from personne WHERE ID LIKE "+txtid.getText());///Nom de la table de la BDD
            while(Rs.next())
            {
                txtno.setText(Rs.getString("nom"));
                txtpre.setText(Rs.getString("prenom"));

            }

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
            
        
        try
        {
            stm=con.ObtenirConnexion().createStatement();
            ///Recupère les ID de la discipline
           ResultSet Rs=stm.executeQuery("Select classe_id,discipline_id from enseignement WHERE personne_id LIKE "+txtid.getText());
           while(Rs.next())
           {
          
           ///Recupère les noms correspond au niveau et à la discipline du niveau et de la discipline
            Rs=stm.executeQuery("Select nom from discipline WHERE ID LIKE "+Rs.getString("discipline_id"));
            
                 while(Rs.next())
                     {
                         txtmat.setText(Rs.getString("nom"));
                      }
          
            }
        }  
            
           
        
        catch(Exception e)
        {
            System.out.println(e);
        }
         
        try
        {
            stm=con.ObtenirConnexion().createStatement();
            ///Recupère les ID du niveau 
           ResultSet Rs=stm.executeQuery("Select classe_id,discipline_id from enseignement WHERE personne_id LIKE "+txtid.getText());
           while(Rs.next())
           {
          
           ///Recupère les noms correspond au niveau et à la discipline du niveau et de la discipline
            Rs=stm.executeQuery("Select nom from niveau WHERE ID LIKE "+Rs.getString("classe_id"));
                  while(Rs.next())
                     {
                    txtniv.setText(Rs.getString("nom"));
                    }
          
            }
        }
            catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detail_prof().setVisible(false);
                new Menu().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detail_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detail_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detail_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detail_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detail_prof().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmat;
    private javax.swing.JTextField txtniv;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtpre;
    // End of variables declaration//GEN-END:variables
}
