/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
<<<<<<< HEAD
=======
import javax.swing.table.DefaultTableModel;
>>>>>>> parent of 00443c0... Possibilité d'ajouter et supprimer note et bulletin


/**
 *
 * @author Victor
 */
public class detail_etud extends javax.swing.JFrame {

    /**
     * Creates new form detail_etud
     */
    Liaison con= new Liaison();
    Statement stm;
    ResultSet Rs;
    PreparedStatement ps;
    
    public detail_etud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpre = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        txtcla = new javax.swing.JTextField();
        txtniv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
<<<<<<< HEAD
=======
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
>>>>>>> parent of 00443c0... Possibilité d'ajouter et supprimer note et bulletin

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Détails de l'étudiant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(240, 10, 551, 100);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Prénom     :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(493, 35, 110, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText(" Niveau       :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 120, 140, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nom            :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 40, 120, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Classe        :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(493, 113, 120, 40);

        txtpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreActionPerformed(evt);
            }
        });
        jPanel2.add(txtpre);
        txtpre.setBounds(630, 40, 100, 30);

        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        jPanel2.add(txtno);
        txtno.setBounds(210, 40, 90, 30);

        txtcla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaActionPerformed(evt);
            }
        });
        jPanel2.add(txtcla);
        txtcla.setBounds(630, 120, 100, 30);

        txtniv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnivActionPerformed(evt);
            }
        });
        jPanel2.add(txtniv);
        txtniv.setBounds(210, 120, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(150, 170, 810, 280);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("ID      :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 120, 80, 30);
        getContentPane().add(txtid);
        txtid.setBounds(480, 120, 80, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Retour au menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(890, 460, 160, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Valider");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(650, 120, 90, 30);

<<<<<<< HEAD
=======
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID du bulletin", "Trimestre", "Appréciation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(290, 390, 500, 150);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Bulletin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(500, 340, 210, 22);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("Détail Bulletin");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(770, 120, 160, 30);

>>>>>>> parent of 00443c0... Possibilité d'ajouter et supprimer note et bulletin
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreActionPerformed

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void txtclaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclaActionPerformed

    private void txtnivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnivActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detail_etud().setVisible(false);
                new Menu().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try
        {
            stm=con.ObtenirConnexion().createStatement();
            ResultSet Rs=stm.executeQuery("Select nom,prenom from personne WHERE ID LIKE "+txtid.getText());///Nom de la table de la BDD
            while(Rs.next())
            {
                txtno.setText(Rs.getString("nom"));
                txtpre.setText(Rs.getString("prenom"));

            }

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
            
       /* try
        {
            stm=con.ObtenirConnexion().createStatement();
            ///Recupère les ID de la discipline
           ResultSet Rs=stm.executeQuery("Select * from enseignement AS e, discipline AS d WHERE e.discipline_id=d.ID AND personne_id LIKE "+txtid.getText());
           while(Rs.next())
                     {
                         txtniv.setText(Rs.getString(""));
                         txtcla.setText(Rs.getString("nom"));
                      }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }*/
        try
        {
            stm=con.ObtenirConnexion().createStatement();
            ///Recupère les ID de la discipline
           ResultSet Rs=stm.executeQuery("Select classe_id from inscription WHERE personne_id LIKE "+txtid.getText());
           while(Rs.next())
           {
          
           ///Recupère les noms correspond au niveau et à la discipline du niveau et de la discipline
            Rs=stm.executeQuery("Select nom,niveau_id from classe WHERE ID LIKE "+Rs.getString("classe_id"));
            
                 while(Rs.next())
                     {
                         txtcla.setText(Rs.getString("nom"));
                         
                         ///Récupère le nom du niveau
                           Rs=stm.executeQuery("Select nom from niveau  WHERE ID LIKE "+Rs.getString("niveau_id"));
                           while(Rs.next())
                           {
                               txtniv.setText(Rs.getString("nom"));
                           }
                      }
          
            }
        }  
            
           
        
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
<<<<<<< HEAD
    }//GEN-LAST:event_jButton4ActionPerformed

=======
        
        
    //Bulletin
        try
        {
            stm=con.ObtenirConnexion().createStatement();
            ///Recupère les ID de la discipline
            Rs=stm.executeQuery("Select ID from inscription WHERE Personne_id LIKE "+txtid.getText());
            if(Rs.next()){
             inscription_ID = Rs.getString("ID");   
            }
             System.out.println(inscription_ID);
            
            Rs=stm.executeQuery("Select ID, Trimestre_id, appreciation from bulletin WHERE Inscription_id LIKE "+inscription_ID);
            while(Rs.next())
            {
                table_bulletin.addRow(new Object[]{Rs.getString("ID"),Rs.getString("Trimestre_id"),Rs.getString("appreciation")});
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        jTable2.setModel(table_bulletin);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detail_etud().setVisible(false);
                new detail_bulletin().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton5ActionPerformed

>>>>>>> parent of 00443c0... Possibilité d'ajouter et supprimer note et bulletin
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detail_etud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detail_etud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detail_etud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detail_etud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detail_etud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
<<<<<<< HEAD
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
=======
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
>>>>>>> parent of 00443c0... Possibilité d'ajouter et supprimer note et bulletin
    private javax.swing.JTextField txtcla;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtniv;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtpre;
    // End of variables declaration//GEN-END:variables
}
